language: python

python:
  - "3.5.2"

# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
    - pip install pytest-cov
    - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres
  
# command to run tests
script: py.test --cov=app app/tests/

after_success:
    - coveralls

env:
  - DEBUG=True
  - CSRF_ENABLED=True
  - SQLALCHEMY_TRACK_MODIFICATIONS=False

  - DB='andela-flask-api'
  - USER='vince'
  - PASSWORD='vince'
  - HOST='localhost'
  - PORT=5432
  - HEROKU_POSTGRESQL_CRIMSON_URL="postgresql://${USER}:${PASSWORD}@${HOST}:5432/${DB}"

  - WTF_CSRF_ENABLED=False
  - SECRET_KEY='youll-never-know-what-it-is-coz-its-secret'
  - MAIL_SERVER='smtp.googlemail.com'
  - MAIL_PORT=465
  - MAIL_USE_TLS=False
  - MAIL_USE_SSL=True
  - MAIL_USERNAME="andelatestmail"
  - MAIL_PASSWORD="andelatestmail1"
  - MAIL_DEFAULT_SENDER="andelatestmail@gmail.com"



#deploy:
#  provider: heroku
#  app: andela-flask-api
#  api_key:
#    secure: "1e9f74ec-b530-4a13-8f18-46c668e018f7"